name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: PWD
      run: echo $PWD
    - name: make
      run: gcc ../../main.c
    - name: execute
      run: ./main
